# Generated by Django 5.0.7 on 2024-07-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='00000000000000', max_length=13, verbose_name='ISBN'),
        ),
    ]
